'use client';
import HeaderPage from '@/components/layout/Header';
import './globals.css';
import { Inter } from 'next/font/google';
import FooterPage from '@/components/layout/Footer';
import 'bootstrap/dist/css/bootstrap.min.css';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
import { usePathname, useSearchParams } from 'next/navigation';
import { useEffect } from 'react';
export default function RootLayout({ children }) {
  const pathname = usePathname();
  return (
    <html lang='en'>
      <body className={inter.className}>
        <HeaderPage pathname={pathname} />
        {children}
        <FooterPage pathname={pathname} />
      </body>
    </html>
  );
}
